# Generated by Django 4.0 on 2021-12-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_location_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('c', 'community'), ('s', 'sales'), ('k', 'knowledge'), ('m', 'misc'), ('t', 'training'), ('d', 'diary'), ('tr', 'trips'), ('o', 'organisation')], max_length=2),
        ),
    ]
